version: '3.8'

services:
  sb_my_practice_db:
    image: mysql:8.0
    container_name: mysql-practice-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SbMyPracticeDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db-practice-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-practice-data:
