openapi: 3.0.0
info:
  title: My Practice API Documentation
  description: This is a sample API documentation
  version: 1.0.0
  contact:
    name: Bang
    email: ecosystemprogramminglanguage@gmail.com
    url: https://example.com
  license:
    name: Licence name
    url: https://some-url.com
servers:
  - url: http://localhost:8082/api/v1
    description: Local ENV
tags:
  - name: Authenticated
    description: Authenticated
paths:
  /auth/signup:
    post:
      summary: Signup
      tags:
        - Authenticated
      requestBody:
        description: Signup request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemberRequestDto'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberResponseDto'
      security:
        - jwtAuth: []
components:
  schemas:
    MemberRequestDto:
      type: object
      properties:
        email:
          type: string
          example: admin@gmail.com
        password:
            type: string
            example: admin
        nickname:
            type: string
            example: Admin
    MemberResponseDto:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - jwtAuth: []
